#!/usr/bin/env python3
"""Rasterize Traditional-Chinese glyphs to 16x16 1-bpp bitmaps -> C header.

Output: cjk_font.h with a codepoint-sorted table for the SSD1306 OLED task.
Each glyph = 32 bytes, row-major, 2 bytes/row, MSB = leftmost pixel.
"""
from PIL import Image, ImageFont, ImageDraw

CHARS = "呼吸心跳狀態有無人數跌倒訊號校準中警次"
FONT_PATH = "/System/Library/Fonts/STHeiti Medium.ttc"
SIZE = 16
PX = 16  # bounding box

font = ImageFont.truetype(FONT_PATH, SIZE)

def glyph_bytes(ch):
    img = Image.new("L", (PX, PX), 0)
    d = ImageDraw.Draw(img)
    # center the glyph in the 16x16 box
    bbox = d.textbbox((0, 0), ch, font=font)
    w = bbox[2] - bbox[0]
    h = bbox[3] - bbox[1]
    ox = (PX - w) // 2 - bbox[0]
    oy = (PX - h) // 2 - bbox[1]
    d.text((ox, oy), ch, fill=255, font=font)
    px = img.load()
    out = []
    for r in range(PX):
        row = 0
        for c in range(PX):
            if px[c, r] >= 128:
                row |= (1 << (15 - c))
        out.append((row >> 8) & 0xFF)
        out.append(row & 0xFF)
    return out

entries = []
for ch in CHARS:
    entries.append((ord(ch), ch, glyph_bytes(ch)))
entries.sort(key=lambda e: e[0])

lines = []
lines.append("/* Auto-generated by gen_cjk_font.py — do not edit. 16x16 1-bpp glyphs. */")
lines.append("#pragma once")
lines.append("#include <stdint.h>")
lines.append("")
lines.append("typedef struct { uint16_t cp; uint8_t bmp[32]; } cjk_glyph_t;")
lines.append("")
lines.append(f"static const cjk_glyph_t CJK_FONT[] = {{")
for cp, ch, b in entries:
    hexb = ",".join(f"0x{x:02X}" for x in b)
    lines.append(f"    {{0x{cp:04X}, {{{hexb}}}}},  /* {ch} */")
lines.append("};")
lines.append(f"#define CJK_FONT_COUNT {len(entries)}")
lines.append("")

out_path = "/Users/thomastang/Documents/ESP32/RuView-src/firmware/esp32-csi-node/main/cjk_font.h"
with open(out_path, "w") as f:
    f.write("\n".join(lines) + "\n")
print(f"wrote {out_path} with {len(entries)} glyphs")

# ASCII preview so we can eyeball the rasterization
for cp, ch, b in entries[:4]:
    print(f"\n{ch} U+{cp:04X}")
    for r in range(PX):
        row = (b[r*2] << 8) | b[r*2+1]
        print("".join("#" if row & (1 << (15-c)) else "." for c in range(PX)))
